name: Pages

on:
  push:
    branches: ["main"]

env:
  XCODE_VERSION: ^26.0-beta

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: macos-15

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: Generate documentation
        run: swift package --allow-writing-to-directory docs generate-documentation --disable-indexing --transform-for-static-hosting --hosting-base-path swift-common --output-path docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
