name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    runs-on: macos-15

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - name: Run tests
      run: swift test -v

  build:
    name: Build for ${{ matrix.platform }}
    runs-on: macos-15
    needs: test
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - platform: iOS
            destination: 'generic/platform=iOS'
          - platform: macCatalyst
            destination: 'platform=macOS,variant=Mac Catalyst'
          - platform: macOS
            destination: 'platform=macOS'
          - platform: tvOS
            destination: 'generic/platform=tvOS'
          - platform: visionOS
            destination: 'generic/platform=visionOS'
          - platform: watchOS
            destination: 'generic/platform=watchOS'

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - name: Build for ${{ matrix.platform }}
      run: |
        xcodebuild build \
          -scheme SwiftCommon-Package \
          -destination '${{ matrix.destination }}' \
          -verbose
